### ISSUE TITLE
Move documention to readthedocs.io

### ISSUE THREAD

**Issue by rcnijzink** [schymans/VOM#35]
Documentation of the VOM is now in a separate folder in html-format, better to move in the future to: https://docs.readthedocs.io/

**Comment by schymans** [comment]
Here is a nice collection of tools to help conversion from html to markdown: http://www.cantoni.org/2013/01/19/converting-html-to-text-markdown
Pandoc seemed to work alright, but manual clean-up is still necessary. The advantage of readthedocs.io is that it can be easily viewed online and it can be automated. The advantage of the current html-based documentation is that it can be easily browsed on the local computer. Could we have the best of both?

**Comment by rcnijzink** [comment]
Also this is included (https://github.com/schymans/VOM/pull/45), so I guess it can be closed.
