### ISSUE TITLE
Slow Run Times compared with Output Sample Run, June 2013 (vom_command=1)

### ISSUE THREAD

**Issue by rarygit** [schymans/VOM#41]
Thanks for VOM, from the literature it seems a very promising tool.

Today I downloaded the *master' version, compiled (gfortran, ubuntu 18.04) & 'make check' (passed OK, quick), which used vom_command=2 as the test.
 
Then ran an sce optimisation using VOM_input data and namelist (i.e. vom_command=1)
This is taking much longer to complete than the run times for the 2013 output sample.

After several hours of restarting and expecting sce_status=1 at least after 90 mins,
no success, so stopped it. 
Intervals between runs were 50 minutes, whereas 2013 is approx. 10 mins.

Is there a significant difference between the 2013 model.x file (using scripts) and this 2019 version (run without scripts)?
Any suggestions would be appreciated to at least match the 2013 run times.

All settings used as in the master VOM_input folder (vom_namelist, vom_command=1 etc)

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2013 Run Times:

 SHUFFLED COMPLEX EVOLUTION OPTIMISER
   Run time:   Tue Jun 18 11:07:48 2013
   Number of model parameters:                    6
   Number of optimisable parameters:              6
   Maximum number of complexes:                   6
   Minimum number of runs per complex:           13
Run time:   Tue Jun 18 11:07:48 2013
NEW Run time:   Tue Jun 18 11:11:55 2013
NEW Run time:   Tue Jun 18 11:30:18 2013
NEW Run time:   Tue Jun 18 11:47:17 2013
NEW Run time:   Tue Jun 18 12:00:42 2013
NEW Run time:   Tue Jun 18 12:11:13 2013
NEW Run time:   Tue Jun 18 12:19:49 2013
NEW Run time:   Tue Jun 18 12:29:04 2013

**Comment by schymans** [comment]
Dear @rarygit, thanks a lot for reporting this issue. @rcnijzink, could you look into this and find out what might have caused the longer run times? I have been wondering about the long run times you reported, too, but I thought it was due to more challenging input files. Maybe this could help to make the VOM-master faster again. I like the pun!

**Comment by rcnijzink** [comment]
I am not sure what causes the longer runtimes, there are no specific differences between the sce-algorithms.  I tried it with the files from the repo in VOM_input, but the first run also just takes about 4mins on my system. I also re-ran the sce with all the same settings some time ago and also then it's just 4-10 minutes before a new runtime starts, took 1.5 hour to converge (on an hpc with 4 cpu's, but still not comparable to your runtimes). @rarygit, can you maybe share the sce_progress.txt file? And how long does a single run take?

**Comment by rarygit** [comment]
$ gfortran --version

GNU Fortran (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0

################################################################


$ sudo lshw -short

H/W path                   Device      Class       Description
==============================================================
                                       system      To Be Filled By O.E.M. (To Be
/0                                     bus         G31M-GS.
/0/0                                   memory      64KiB BIOS
/0/4                                   processor   Intel(R) Core(TM)2 CPU       
/0/4/5                                 memory      64KiB L1 cache
/0/4/6                                 memory      4MiB L2 cache
/0/e                                   memory      4GiB System Memory
/0/e/0                                 memory      2GiB DIMM SDRAM Synchronous
/0/e/1                                 memory      2GiB DIMM SDRAM Synchronous
/0/100                                 bridge      82G33/G31/P35/P31 Express DRA
/0/100/1                               bridge      82G33/G31/P35/P31 Express PCI
/0/100/1/0                             display     Bonaire XTX [Radeon R7 260X/3
/0/100/1/0.1                           multimedia  Tobago HDMI Audio [Radeon R7 
/0/100/1b                              multimedia  NM10/ICH7 Family High Definit
/0/100/1c                              bridge      NM10/ICH7 Family PCI Express 
/0/100/1c/0                            bus         VL80x xHCI USB 3.0 Controller
/0/100/1c/0/0              usb6        bus         xHCI Host Controller
/0/100/1c/0/0/1                        bus         USB2.0 Hub
/0/100/1c/0/0/1/4          scsi6       storage     My Passport 0837
/0/100/1c/0/0/1/4/0.0.0    /dev/sdf    disk        1TB My Passport 0837
/0/100/1c/0/0/1/4/0.0.0/1  /dev/sdf1   volume      97GiB Windows FAT volume
/0/100/1c/0/0/1/4/0.0.0/2  /dev/sdf2   volume      833GiB Linux filesystem parti
/0/100/1c/0/0/1/4/0.0.1                generic     SES Device
/0/100/1c/0/1              usb7        bus         xHCI Host Controller
/0/100/1c/0/1/2            scsi4       storage     Elements 25A2
/0/100/1c/0/1/2/0.0.0      /dev/sde    disk        2TB Elements 25A2
/0/100/1c/0/1/2/0.0.0/1    /dev/sde1   volume      1862GiB EXT3 volume
/0/100/1c/0/1/3            scsi5       storage     My Passport 259F
/0/100/1c/0/1/3/0.0.0      /dev/sdd    disk        1TB My Passport 259F
/0/100/1c/0/1/3/0.0.0/1    /dev/sdd1   volume      931GiB Linux filesystem parti
/0/100/1c/0/1/3/0.0.1                  generic     SES Device
/0/100/1c.1                            bridge      NM10/ICH7 Family PCI Express 
/0/100/1c.1/0              enp1s0      network     RTL8111/8168/8411 PCI Express
/0/100/1d                              bus         NM10/ICH7 Family USB UHCI Con
/0/100/1d/1                usb2        bus         UHCI Host Controller
/0/100/1d.1                            bus         NM10/ICH7 Family USB UHCI Con
/0/100/1d.1/1              usb3        bus         UHCI Host Controller
/0/100/1d.1/1/1                        input       SiliconWin mouse
/0/100/1d.1/1/2                        input       Microsoft
/0/100/1d.2                            bus         NM10/ICH7 Family USB UHCI Con
/0/100/1d.2/1              usb4        bus         UHCI Host Controller
/0/100/1d.3                            bus         NM10/ICH7 Family USB UHCI Con
/0/100/1d.3/1              usb5        bus         UHCI Host Controller
/0/100/1d.7                            bus         NM10/ICH7 Family USB2 EHCI Co
/0/100/1d.7/1              usb1        bus         EHCI Host Controller
/0/100/1d.7/1/6            scsi7       storage     USB Storage
/0/100/1d.7/1/6/0.0.0      /dev/sdg    disk        STORAGE DEVICE
/0/100/1d.7/1/6/0.0.0/0    /dev/sdg    disk        
/0/100/1e                              bridge      82801 PCI Bridge
/0/100/1f                              bridge      82801GB/GR (ICH7 Family) LPC 
/0/100/1f.1                            storage     82801G (ICH7 Family) IDE Cont
/0/100/1f.2                            storage     NM10/ICH7 Family SATA Control
/0/100/1f.3                            bus         NM10/ICH7 Family SMBus Contro
/0/1                       scsi0       storage     
/0/1/0.0.0                 /dev/cdrom  disk        DVD-ROM SH-D162C
/0/1/0.1.0                 /dev/cdrw   disk        DRW-1814BL
/0/2                       scsi2       storage     
/0/2/0.0.0                 /dev/sda    disk        64GB SAMSUNG SSD 830
/0/2/0.0.0/1               /dev/sda1   volume      1GiB EXT4 volume
/0/2/0.0.0/2               /dev/sda2   volume      58GiB Linux LVM Physical Volu
/0/2/0.1.0                 /dev/sdb    disk        64GB SanDisk SDSSDHP0
/0/2/0.1.0/1               /dev/sdb1   volume      56GiB EXT4 volume
/0/2/0.1.0/2               /dev/sdb2   volume      3261MiB Extended partition
/0/2/0.1.0/2/5             /dev/sdb5   volume      3261MiB Linux swap volume
/0/3                       scsi3       storage     
/0/3/0.0.0                 /dev/sdc    disk        64GB SAMSUNG SSD 830
/0/3/0.0.0/1               /dev/sdc1   volume      59GiB EXT4 volume



##################################################################################


$ hwinfo --short

cpu:                                                            
                       Intel(R) Core(TM)2 CPU          6420  @ 2.13GHz, 2090 MHz
                       Intel(R) Core(TM)2 CPU          6420  @ 2.13GHz, 2085 MHz
keyboard:
  /dev/input/event3    Microsoft Nano Transceiver v1.0 for Bluetooth
mouse:
  /dev/input/mice      Microsoft Nano Transceiver v1.0 for Bluetooth
  /dev/input/mice      SiliconWin mouse
monitor:
                       VIEWSONIC VX2433wm
graphics card:
                       ATI Bonaire XTX [Radeon R7 260X/360]
sound:
                       ATI Tobago HDMI Audio [Radeon R7 360 / R9 360 OEM]
                       Intel NM10/ICH7 Family High Definition Audio Controller
storage:
                       Intel NM10/ICH7 Family SATA Controller [IDE mode]
                       Intel 82801G (ICH7 Family) IDE Controller
network:
  enp1s0               Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
network interface:
  lo                   Loopback network interface
  enp1s0               Ethernet network interface
disk:
  /dev/sdf             WD My Passport 0837
  /dev/sdd             WD My Passport 259F
  /dev/sdb             SanDisk SDSSDHP0
  /dev/sdg             Generic STORAGE DEVICE
  /dev/sde             WD Elements 25A2
  /dev/sdc             SAMSUNG SSD 830
  /dev/sda             SAMSUNG SSD 830
partition:
  /dev/sdf1            Partition
  /dev/sdf2            Partition
  /dev/sdd1            Partition
  /dev/sdb1            Partition
  /dev/sdb2            Partition
  /dev/sdb5            Partition
  /dev/sde1            Partition
  /dev/sdc1            Partition
  /dev/sda1            Partition
  /dev/sda2            Partition
cdrom:
  /dev/sr0             TSSTcorp DVD-ROM SH-D162C
  /dev/sr1             ASUS DRW-1814BL
usb controller:
                       Intel NM10/ICH7 Family USB UHCI Controller #4
                       VIA VL80x xHCI USB 3.0 Controller
                       Intel NM10/ICH7 Family USB UHCI Controller #2
                       Intel NM10/ICH7 Family USB UHCI Controller #3
                       Intel NM10/ICH7 Family USB UHCI Controller #1
                       Intel NM10/ICH7 Family USB2 EHCI Controller
bios:
                       BIOS
bridge:
                       Intel NM10/ICH7 Family PCI Express Port 1
                       Intel 82801GB/GR (ICH7 Family) LPC Interface Bridge
                       Intel 82G33/G31/P35/P31 Express PCI Express Root Port
                       Intel 82801 PCI Bridge
                       Intel 82G33/G31/P35/P31 Express DRAM Controller
                       Intel NM10/ICH7 Family PCI Express Port 2
hub:
                       Linux Foundation 2.0 root hub
                       Linux Foundation 1.1 root hub
                       VIA Hub
                       Linux Foundation 3.0 root hub
                       Linux Foundation 1.1 root hub
                       Linux Foundation 2.0 root hub
                       Linux Foundation 1.1 root hub
                       Linux Foundation 1.1 root hub
memory:
                       Main Memory
unknown:
                       FPU
                       DMA controller
                       PIC
                       Keyboard controller
  /dev/lp0             Parallel controller
                       Intel NM10/ICH7 Family SMBus Controller
                       Serial controller
  /dev/input/event7    Microsoft Nano Transceiver v1.0 for Bluetooth


################################################################

**Comment by rcnijzink** [comment]
Hi @rarygit, thanks for the info, I think it may have to do with the parallel-part of the sce-algorithm. You could try to set n_thread=1 in the vom_namelist, I noted it's set to 4 in the repository, and I think your pc cannot handle that.

But this is also why ask the file sce_progress.txt, the first initial loop is not parallel and just uses one cpu, if after the initial loop runtimes go up, we know we should look there. Besides, I wonder what values for the NCP you get. Usually when runtimes go up, the algorithm has difficulties by finding good solutions, e.g. when only negative NCP-values are found. This could indicate there is something going wrong with the input part. 

Also, I noticed the runtime_limit is set to 5 in the namelist, but when you don't have limitations on your pc, you can set this to much higher values. It is meant in case you run the VOM on an HPC where you have to finish the task in a few hours. There should also be no need to restart the VOM when you set this to a large number. Now the program will stop as quickly as possible when 5 minutes have passed.

**Comment by rarygit** [comment]
Very helpful information to understand the program.I will try this. 28.10.2019, 10:16, "rcnijzink" <notifications@github.com>:Hi @rarygit, thanks for the info, I think it may have to do with the parallel-part of the sce-algorithm. You could try to set n_thread=1 in the vom_namelist, I noted it's set to 4 in the repository, and I think your pc cannot handle that.But this is also why ask the file sce_progress.txt, the first initial loop is not parallel and just uses one cpu, if after the initial loop runtimes go up, we know we should look there. Besides, I wonder what values for the NCP you get. Usually when runtimes go up, the algorithm has difficulties by finding good solutions, e.g. when only negative NCP-values are found. This could indicate there is something going wrong with the input part.Also, I noticed the runtime_limit is set to 5 in the namelist, but when you don't have limitations on your pc, you can set this to much higher values. It is meant in case you run the VOM on an HPC where you have to finish the task in a few hours. There should also be no need to restart the VOM when you set this to a large number.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rarygit** [comment]
I see, I didn't send you the output from tt1-2 (vom_command=2)As attached. Ran it now, with positive carbon profit: $ ./model.xStart single calculation with parameters...Cumulative error in water balance (initial Ws+Input-Output-final Ws, in m): -1.4000507952971475E-007Number of times dtsu was limiting: 1026Number of times dtmax was limiting: 402929Model run COMPLETE The carbon profit achieved is: 3092.6310762014177Hourly results are saved in resulthourly.txtDaily results are saved in resultsdaily.txtYearly results are saved in yearly.txtSoil results are saved in delyudaily.txt, rsurfdaily.txt, ruptkhourly.txt, suvechourly.txtProgram terminated    28.10.2019, 10:16, "rcnijzink" <notifications@github.com>:Hi @rarygit, thanks for the info, I think it may have to do with the parallel-part of the sce-algorithm. You could try to set n_thread=1 in the vom_namelist, I noted it's set to 4 in the repository, and I think your pc cannot handle that.But this is also why ask the file sce_progress.txt, the first initial loop is not parallel and just uses one cpu, if after the initial loop runtimes go up, we know we should look there. Besides, I wonder what values for the NCP you get. Usually when runtimes go up, the algorithm has difficulties by finding good solutions, e.g. when only negative NCP-values are found. This could indicate there is something going wrong with the input part.Also, I noticed the runtime_limit is set to 5 in the namelist, but when you don't have limitations on your pc, you can set this to much higher values. It is meant in case you run the VOM on an HPC where you have to finish the task in a few hours. There should also be no need to restart the VOM when you set this to a large number.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rarygit** [comment]
Following Remko's suggestions, attached is the output for latest optimisation simulation tt2-1. i_maxyear=30vom_command=1n_thread=1runtime_limit=500 Start Run time: Mon Oct 28 10:15:59 2019Finish Run time: Mon Oct 28 15:02:38 2019Total Run time (uninterrupted): approx. 04 hrs 45 mins ################################################################## 26.10.2019, 12:28, "schymans" <notifications@github.com>:Dear @rarygit, thanks a lot for reporting this issue. @rcnijzink, could you look into this and find out what might have caused the longer run times? I have been wondering about the long run times you reported, too, but I thought it was due to more challenging input files. Maybe this could help to make the VOM-master faster again. I like the pun!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rcnijzink** [comment]
Hi @rarygit, I don't see an attachement, can you add it in the github discussion? Should look like this: 
[sce_progress.txt](https://github.com/schymans/VOM/files/3782089/sce_progress.txt)

**Comment by rarygit** [comment]
Hi @rcnijzink, hopefully this shows it: 

[sce_progress.txt](https://github.com/schymans/VOM/files/3782131/sce_progress.txt)

**Comment by rarygit** [comment]
And this is the tt2-1 simulation:

[tt2-1.zip](https://github.com/schymans/VOM/files/3782148/tt2-1.zip)

**Comment by rcnijzink** [comment]
Hi @rarygit, I ran everything based on the zip tt2-1, and here it took 1.5 hours to complete. See also attached. So I am not sure what is causing your slow runtimes, but it must be depend on your local architecture. You could try setting n_thread to 2, but that will occupy your pc quite a bit. If you really want to speed things up, you could also try to increase the soil layer thickness (i_delz), or the total soil depth, but these may influence your final results. Similarly, reducing the timeseries should also speed things up, but you need quite a long time series to get good estimates of the vegetation properties.
[sce_progress.txt](https://github.com/schymans/VOM/files/3787389/sce_progress.txt)

**Comment by rarygit** [comment]
Thanks @rcnijzink, this was helpful. The faster machine (i7, 2 x gpu) is needed for ms win. 
With your suggestions I can leave the linux machine running VOM by itself.
If you want, you can close this issue.
I will send a separate email to both of you, outlining what I intended to use VOM for, and whether that idea is feasible.

**Comment by schymans** [comment]
Thanks for helping resolve the issue!
