### ISSUE TITLE
If the file "sce_status.txt" appears, the model has to be run one more time

### ISSUE THREAD

**Issue by rarygit** [schymans/VOM#42]
Is there a forum to ask questions related to running & using the program?

The manual states:
"If the file "sce_status.txt" appears, the model has to be run one more time to write the results obtained with the optimised parameter set to the disc. This does not take long. Also see below."
See below where?

Ambiguously, does that mean: again run in the terminal   $ ./model.x 

That produces:  $ ./model.x
 Restarting SCE from previous run...
 ERROR: cannot restart from this state:
 SCE already converged 

Alternatively, does running the model one more time mean to use switch "vom_command=2" in the vom_namelist and run the optimised parameter set (sce_lastbest.txt) in the pars.txt file?

Thanks for clarification.

**Comment by rarygit** [comment]
It seems that release AoB2015 (Version of code used for Schymanski et al. 2015) /VOM_docu / HowToRun.html might have the answer. Using sce_lastbest.txt instead of finalbest.txt and pars.txt instead of shuffle.par. Mind the step where you delete the last value.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Compute results

As mentioned above you can create result files after "finalbest.txt" is written by running the model once again.

finalbest.txt

This file is created by the model if optimised values are found. There is no need to adapt the shuffle.par (first word in the first line is 0 or 2). Just start the model once again. You can also use values of pars.txt. Just add a space and 0 at the end of the file and rename it to finalbest.txt.

There are two more options to create result files.

currentbest.txt

This file is created by the model runs before finalbest.txt appears and holds the optimal values up to this model run. It has the same structure like finalbest.txt. You can calculate the result files with currentbest.txt by setting the first word in the first line of shuffle.par to 2 and starting the model once again.

pars.txt

You have to create this file by your own e.g. copying values out from finalbest.txt. It has the same structure like finalbest.txt but without the last value. If you want to use the finalbest.txt, delete the last value and rename the file to pars.txt. It can be used to calculate just the best ncp and writes this to one result file (model_output.txt). To do this you have to set the first word in the first line of shuffle.par to 3 and starting the model once again.

**Comment by schymans** [comment]
@rarygit, thanks a lot for reporting (and clarifying) this glitch in the documentation. @rcnijzink, could you update the documentation to more clearly reflect the new run procedure? Thanks!!

**Comment by rcnijzink** [comment]
See https://github.com/schymans/VOM/pull/43

**Comment by schymans** [comment]
I merged #43, but the behaviour is not very convenient. Basically, we should change coreprog.f90 line 115 to not just stop if sce_status.txt appears, but instead read in sce_bestpars.txt or sce_lastbest.txt and proceed to calculating the results.
