### ISSUE TITLE
Inconsistent naming of foliage cover-related variables

### ISSUE THREAD

**Issue by schymans** [schymans/VOM#57]
Here are the relevant lines from modules.f90:
```
      REAL*8  :: o_cai                  ! Projected cover perennial vegetation (0-1)
      REAL*8  :: pcg_d(3)               ! Projected cover seasonal vegetation (pcg_d(2) is actual value)
      REAL*8  :: lai_lt(3)              ! Local leaf area index trees
      REAL*8  :: lai_lg(3)              ! Local leaf area index grasses
```
and transpmodel.f90:
```
      REAL*8 :: Ma_lg(3)      !fraction of absorbed radiation grasses
      REAL*8 :: Ma_lt(3)      !fraction of absorbed radiation trees
```
Projected cover is usually referred to 1 minus the fraction of bare soil seen from above. This would be equivalent to `o_cai*Ma_lt + pcg_d*Ma_lg`. Therefore, o_cai and pcg_d should be renamed to crown area index (0-1), and Ma_lg and Ma_lt should be called the 'Local fraction of absorbed radiation...'. This would be more consistent with the fact that `pcg_d(1) * Ma_lg(ii)` is used to compute jact and rl for grasses.

**Comment by rcnijzink** [comment]
This one should have been closed by https://github.com/schymans/VOM/pull/60
