### ISSUE TITLE
Correct formulation of Jmax

### ISSUE THREAD

**Issue by rcnijzink** [schymans/VOM#61]
By going over the 2007-paper, and coding up some of the equations in Jupyter (https://git.list.lu/remko.nijzink/lai_fpar/-/blob/master/notebooks/lai_equations.ipynb), I noticed that the calculation of Jmax in the VOM is dimensionally inconsistent. In the VOM, it is this code:

```
!     * (Out[310], derived from (3.26)) Temperature dependence of Jmax
      jmaxg_h(:) = (p_E ** ((i_ha * (-25.d0 + tair_h(th_)) * (-273.d0  &
     &           + topt_ + 273.d0 * p_R_ * topt_)) / ((25.d0 + 273.d0  &
     &           * p_R_ * topt_) * (tair_h(th_) + 273.d0 * p_R_        &
     &           * topt_))) * ((-1.d0 + p_E ** (-(i_hd * (-298.d0      &
     &           + topt_)) / (25.d0 + 273.d0 * p_R_ * topt_))) * i_ha  &
     &           + i_hd) * jmax25g_d(:)) / ((-1.d0 + p_E ** ((i_hd     &
     &           * (273.d0 + tair_h(th_) - topt_)) / (tair_h(th_)      &
     &           + 273.d0 * p_R_ * topt_))) * i_ha + i_hd)
```

In Jupyter, this is:

![jmax1](https://user-images.githubusercontent.com/8998623/107193155-d0bb4980-69ee-11eb-9148-eea1438c59da.png)

However, the old documentation, says this:

![jmax3](https://user-images.githubusercontent.com/8998623/107193174-d7e25780-69ee-11eb-937f-8777702b23ed.png)

Looks like the conversions from air temperature to kelvin have gone wrong with the parenthesis. I put the above also in Jupyter:

![jmax2](https://user-images.githubusercontent.com/8998623/107193195-dd3fa200-69ee-11eb-8c0a-21207adfe40d.png)

The differences seem not too big fortunately:

![jmax_graph](https://user-images.githubusercontent.com/8998623/107193229-e92b6400-69ee-11eb-938a-2bd0c76135b2.png)

**Comment by schymans** [comment]
Indeed, I don't know what happened there. It is not just a missing bracket. Basically, only this part is correct: 
```fortran
                            * ((-1.d0 + p_E ** (-(i_hd * (-298.d0      &
     &           + topt_)) / (25.d0 + 273.d0 * p_R_ * topt_))) * i_ha  &
     &           + i_hd) * jmax25g_d(:)) / ((-1.d0 + p_E ** ((i_hd     &
     &           * (273.d0 + tair_h(th_) - topt_)) / (tair_h(th_)      &
     &           + 273.d0 * p_R_ * topt_))) * i_ha + i_hd)
```
Right?

**Comment by rcnijzink** [comment]
Yes, especially the first part was wrong, so it is now:

```
      jmaxg_h(:) = (p_E ** ((i_ha * (-25.d0 + tair_h(th_)))                 &
        &           / ((25.d0 + 273.d0)  * p_R_ * (tair_h(th_) + 273.d0) )) &
        &           * ((-1.d0 + p_E ** (-(i_hd * (-298.d0                   &
        &           + topt_)) /( (25.d0 + 273.d0) * p_R_ * topt_))) * i_ha  &
        &           + i_hd) * jmax25g_d(:)) / ((-1.d0 + p_E ** ((i_hd       &
        &           * (273.d0 + tair_h(th_) - topt_)) / ( (tair_h(th_)      &
        &           + 273.d0) * p_R_ * topt_))) * i_ha + i_hd)

```
